import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from 'next/font/google';
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import AuthProvider from "./context/auth-context";
import { ListProvider } from "./context/list-context";
import { NotificationProvider } from "./context/notification-provider";
import { FavoritesProvider } from "./context/favorites-context";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const montserrat = Montserrat({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
    display: 'swap',
    variable: '--font-montserrat',
});

export const metadata: Metadata = {
    title: "SWList",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${montserrat.variable} ${montserrat.variable} antialiased`}
            >
                <NotificationProvider>
                    <AuthProvider>
                        <FavoritesProvider>
                            <ListProvider>
                                <ThemeProvider attribute='class' enableSystem defaultTheme="system">
                                    <Header />
                                    {children}
                                    <Footer />
                                </ThemeProvider>
                            </ListProvider>
                        </FavoritesProvider>
                    </AuthProvider>
                </NotificationProvider>
            </body>
        </html>
    );
}
